### PR TITLE
Expand feature set

### PR DESCRIPTION
**Pull request by renemarc**
Many thanks for your Lightpack component @mihalski, and for your related feature requests on the [Lightpack Fork](https://github.com/psieg/Lightpack) and on [py-lightpack](https://github.com/tremby/py-lightpack).

I've played with your code and added some useful features, mostly to allow for color and brightness control. It's pending on [my changes](https://github.com/tremby/py-lightpack/pull/2) being accepted by @tremby to his library and pushed to [PyPi](https://pypi.org/project/py-lightpack/), but here are the updates, with some of them inspired by the LIFX component. They are tested on API 2.2 yet should degrade gracefully.

New features:
- Async support
- API key support
- Brightness control (if available)
- Color control with persistence (if available)
- Addressable zones (if available)
- Service handler to apply changes without having to turn the Lightpack on
- Type hinting
- Cleanup on shutdown

However, having so many updates in one go means that this PR has plenty of code changes. 👀

Hopefully we could bring your component into Home Assistant codebase soon so that it becomes a 1st-degree citizen there! 😃

### CODE REVIEW

**Comment by dobrynski** [comment]
I didn't realise anyone apart from me (and maybe one other person) actually used it!

I'm not much of a programmer (yet?) but some time ago I had brightness/colour (sort of) working using the py-colour library (for silent alerts/notifications). Was also using a slightly enhanced py-lightpack, but all of it was lost in a crash and I never got back to it. And I never got reconnecting after unavailability working properly.

You've just done everything I had hoped to (maybe one day) do and plenty more! Thank you for your contribution :)

**Comment by tremby** [comment]
Well I had no idea anybody used py-lightpack, so isn't this nice!

**Comment by dobrynski** [comment]
I've been testing out your improvements and everything has been working perfectly. Really great work!

Had a weird issue where the REQUIREMENTS would not install without any form of warning or error to say it even tried to download and/or install. This will hopefully fix itself once your enhancements to py-lightpack make it into a release version.

**Comment by dobrynski** [comment]
I updated to the new HA 0.88.0 component structure at my end, but I was still having the same problem with the requirements. I now discovered that it's not just me!

https://community.home-assistant.io/t/lightpack-assistance/102790?u=mihalski

Oh and I'm using `REQUIREMENTS = ['py-lightpack==2.2.0']`.
And like I mentioned in the post on the community website, why does the py-lightpack library need to be in the root folder of site-packages?

**Comment by grantclem** [comment]
Hi,

I am not having any issues with mine - even when it goes into deep standby after midnight it appears ok. Not I generally use the harmony remote via Alexa to turn it on. Which appears to work like a “Wake on LAN” anyway.

**Comment by dobrynski** [comment]
This problem is about getting it to work at all.
It cannot install the required libraries and therefore cannot load. You must manually download the required libraries and put them in the dips folder and then it works fine, but it does not happen automatically the way it should.
There is definitely some sort of problem somewhere.

**Comment by grantclem** [comment]
Bump up to 0.89b1 and see if works?

**Comment by dobrynski** [comment]
Try purging the deps folder and restarting?
It may shock the few of you using this but I do not have a dev environment :/ I never figured out how to set it up in a useful way as I use PyCharm.
That's one of many TODO's for this year.

**Comment by dobrynski** [comment]
And another user: https://github.com/mihalski/homeassistant/issues/2

**Pull request merged**
